services:
  app:
    image: tools.numbertowordsconversion.web
    build:
      context: .
      dockerfile: ./Tools.NumberToWordsConversion.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5170;http://+:5169
      - ASPNETCORE_HTTPS_PORT=5170
      - ASPNETCORE_Kestrel:Certificates:Default:Password=password
      - ASPNETCORE_Kestrel:Certificates:Default:Path=/cert/aspnetapp.pfx
    ports:
      - "5169:5169"
      - "5170:5170"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/cert:ro